# -*- coding: utf-8 -*-
"""exposearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ymy6cAL1MIJRRQtUPVVKh6ATvcoEZCHu
"""

def binary_search(arr,target,left,rigth):
  while left<=rigth:
    mid=(left+rigth)//2
    if arr[mid]==target:
      return mid
    elif arr[mid]<target:
      left=mid+1
    else:
      rigth=mid-1
  return -1

def expo_search(arr,target):

  if not arr:
    return -1
  n=len(arr)
  i=1
  while i<n and arr[i]<=target:

    i*=2
  return binary_search(arr,target,i//2,min(i,n-1))

arr=[2,4,6,8,10,12,14]
target = 10
result = expo_search(arr, target)
print(f"Element {target} found at index:{result}")

