# -*- coding: utf-8 -*-
"""insertionsort _strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11imVfLMmsicjwY7bzSClk8MV5trTd9eb
"""

def insertion_sort(arr):
    for i in range(1,len(arr)):
        key=arr[i]
        j=i-1
        while j>=0 and arr[j]>key:
            arr[j+1]=arr[j]
            j-=1
        arr[j+1]=key
    return arr
text=input("Enter a string:")
ch=list(text)
print(ch)
sort_chars=insertion_sort(ch)
print(ch)
print("Sorted array :",''.join(ch))

