# -*- coding: utf-8 -*-
"""linear search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_H6bryQshaxZPwd6Xum13DAmDRMAHSt
"""

''' linear search ins sorted array
[45,-9,77,32]
1.arr of list of size n
2.key for search element
3.start with zero index value
4.compare arr[i]==key
        arr[i]=key return index
        else not(move to next index)
5.repeat same steps till n-1
6.if no match return -1

#program
def linear_search(arr,key):
    for i in range(len(arr)):
        if arr[i]==key:
            return i
    return -1
size=int(input("enter the size of array:"))
arr=[]
print("Enter the elements:")
for i in range(size):
  num=int(input(f"Elements {i+1}:"))
  arr.append(num)
key = int(input("Enter the key to search:"))
result= linear_search(arr,key)
if result != -1:
    print(f"\n Element {key} found at index {result}.")
else:
    print(f"\nElement {key} not found in the array.")







