# -*- coding: utf-8 -*-
"""Palindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1og6X-T95zkUPE6bpOPdWSjRs4VF9DteW
"""

''''program to check wheather the give string is palindrome or not and count the palandromic characters which are repeated
str=madam
output:{'m':2,'a':2,'d':1}
str=malayalam'''

text=input("enter the name:")
if text==text[::-1]:
    print("palindrome")
else:
    print("Not a palindrome")
freq={}
for ch in text:
    freq[ch]=freq.get(ch,0)+1
print(freq)

