# -*- coding: utf-8 -*-
"""selectionsort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHQnz3QkGmIVSyYFVnuGgmSqRcK1pK1T
"""

'''
1.start from the first element in the list/array
2.arr[0]=min
3.compare with all the remaining elements to find the real lowest element
4.perform swapping with current position
5.repeat the smae with adding positional values for each ,min check

for -> 0 to n-1:
        min=i
        for j-> i+1 to n:
               if arr[j]<arr[mib]
                        swap
mmin=i+1'''

def selection_sort(arr):
    n=len(arr)
    for i in range(n):
        min_index=i
        for j in range(i+1,n):
            if arr[j]<arr[min_index]:
                min_index=j
        arr[i],arr[min_index]=arr[min_index],arr[i]
    return arr



size=int(input("Enter the number of elements:"))
arr=[]
print("Enter",size,"Elements")
for _ in range(size):
    num=int(input())
    arr.append(num)
result= selection_sort(arr)
print("Sorted Array:",result)

2
